### ISSUE TITLE
Update Resp setelah login

### ISSUE THREAD

**Issue by buddyy93** [detautama/mh-cm-su#11]
{
	token: "YWRtaW5AZ21haWwuY29tOmFkbWlu",
	username: "admin",
	statusM: {
		statusBl: {
			status: "",
			user_id: "",
			token: ""
		},
		statusSP: {
			status: "",
			user_id: "",
			token: ""
		},
		statusTP: {
			status: "",
			user_id: "",
			token: ""
		},
	}
}

**Comment by detautama** [comment]
![image.png](https://images.zenhubusercontent.com/5b002db84b5806bc2bd3ce01/653b38fb-75ef-485a-ab38-73c87b85eb22)
